### ISSUE TITLE
shared memory was locked

### ISSUE THREAD

**Issue by Veluu** [vozlt/nginx-module-vts#72]
nginx-1.10.3 and vts-0.1.13 all I can see in nginx logs is
```Mar 07 10:47:28 myhost nginx[18544]: 2017/03/07 10:47:28 [notice] 18544#0: signal 17 (SIGCHLD) received
Mar 07 10:47:28 myhost nginx[18544]: 2017/03/07 10:47:28 [alert] 18544#0: worker process 18753 exited on signal 11

Mar 07 10:47:28 myhost nginx[18544]: 2017/03/07 10:47:28 [alert] 18544#0: shared memory zone "ngx_http_vhost_traffic_status" was locked by 18753

Mar 07 10:47:28 myhost nginx[18544]: 2017/03/07 10:47:28 [notice] 18544#0: start worker process 18797

Mar 07 10:47:28 myhost nginx[18544]: 2017/03/07 10:47:28 [notice] 18544#0: signal 29 (SIGIO) received

Mar 07 10:47:28 myhost nginx[18544]: 2017/03/07 10:47:28 [debug] 18797#0: opened /dev/urandom 76 for pid 18797

Mar 07 10:47:29 myhost nginx[18544]: 2017/03/07 10:47:29 [notice] 18544#0: signal 17 (SIGCHLD) received

Mar 07 10:47:29 myhost nginx[18544]: 2017/03/07 10:47:29 [alert] 18544#0: worker process 18569 exited on signal 11

Mar 07 10:47:29 myhost nginx[18544]: 2017/03/07 10:47:29 [alert] 18544#0: shared memory zone "ngx_http_vhost_traffic_status" was locked by 18569

Mar 07 10:47:29 myhost nginx[18544]: 2017/03/07 10:47:29 [notice] 18544#0: start worker process 18800

Mar 07 10:47:29 myhost nginx[18544]: 2017/03/07 10:47:29 [notice] 18544#0: signal 29 (SIGIO) received

Mar 07 10:47:29 myhost nginx[18544]: 2017/03/07 10:47:29 [debug] 18800#0: opened /dev/urandom 76 for pid 18800``

**Comment by vozlt** [comment]
Thanks for the report.
I fixed suspected parts just now and re-tagged to v0.1.13.
Please test.

Latest commit: https://github.com/vozlt/nginx-module-vts/commit/701e32987c2d1a56868941df2ecb23bd793e8da9

**Comment by Veluu** [comment]
Thank you for a fast response. I still get

``[alert] 908#0: worker process 6605 exited on signal 11``

**Comment by Veluu** [comment]
Ok it looks it works when I increased mem in vhost_traffic_status_zone

**Comment by vozlt** [comment]
Please check the below:

1. If nginx-module-vts is disabled like `vhost_traffic_status off`, does it occur?
2. Did it occur in nginx-module-vts-v0.1.12?
3. Did it occur in nginx-1.11.10 + nginx-module-vts-v0.1.13?
4. If minimum set like the below(on | off), does it occur?
```Nginx
...
vhost_traffic_status off;
server {
    listen 80;
    server_name localhost;
    location / {
        root /var/www;
    }
}
```
```Nginx
...
vhost_traffic_status on;
server {
    listen 80;
    server_name localhost;
    location / {
        root /var/www;
    }
}
```
`$ tail -f /var/log/nginx/error.log`
`$ curl http://localhost`

5. If not occur in case of the above 4, could I get a configuration that occuring it?
6. The best way to solve is a core dump. Could I get a gdb backtrace like https://github.com/vozlt/nginx-module-vts/issues/71?

**Comment by robsonpeixoto** [comment]
@Veluu Which value that you are using in vhost_traffic_status_zone?

**Comment by vozlt** [comment]
The best way to slove the segfault is a gdb backtrace after core dump like https://github.com/vozlt/nginx-module-vts/issues/71.
Anyway I'm not sure if the above case is also effective, I have an update to prevent segfault if the shared memory is not enough.
Also I added **sharedZones** parts in JSON to support shared memory information it can be prevent the shortage by expect shared memory usage in advance. 

@Veluu: Please test if the segfault occurs in latest commit the follows: 

Latest commit: https://github.com/vozlt/nginx-module-vts/commit/50a88b1ff5e86cca02a4ebfe3f23eb8b2ce8986b
